In [3]:
import time
import numpy as np
start = time.time()
l = [x*x for x in range(100000)]
end = time.time()
print('time with lists :',start-end)
start = time.time()
a=np.arange(100000)
a=a*a
end = time.time()

print(end-start)


time with lists : -0.015623331069946289
0.0


### trignometric functions

In [4]:
a= np.random.randint(100,size =23)
np.sin(a)

array([-0.94828214, -0.77946607,  0.89399666, -0.75098725, -0.53657292,
       -0.521551  ,  0.77389068, -0.24525199,  0.96836446,  0.0353983 ,
       -0.24525199,  0.31322878, -0.7391807 ,  0.41211849, -0.99999021,
       -0.96139749,  0.14987721,  0.43616476, -0.40403765,  0.76255845,
       -0.98803162,  0.43616476,  0.27090579])

In [5]:
np.sin(3.14/2)

0.9999996829318346

In [6]:
np.arcsin(1)

1.5707963267948966

In [7]:
np.rad2deg(1.5707963267948966)

90.0

In [8]:
np.deg2rad(90)

1.5707963267948966

In [9]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [10]:
math.sin([2,3])

TypeError: must be real number, not list

Log and Exponentional functions

In [11]:
print(np.log(2))
print(np.log(1))

0.6931471805599453
0.0


In [12]:
print(np.log2(2))
print(np.log2(32))
print(np.log(np.exp(1)))

1.0
5.0
1.0


In [13]:
# np.log(0)


In [14]:
np.log1p(2)
# np.log1p

1.0986122886681098

In [15]:
np.log(2+1)

1.0986122886681098

In [16]:
print(np.exp(1))

2.718281828459045


In [17]:
print(np.exp2(2))

4.0


In [18]:
print(np.expm1(5))
print(np.exp(5)-1)
# np.expm1(x)=np.exp(x)-1

147.4131591025766
147.4131591025766


Statastics

In [19]:
a

array([93, 92, 90, 18, 12, 56, 70, 94, 83, 88, 94, 82, 62,  9, 11, 17, 19,
       57, 31, 26, 30, 57, 28])

In [20]:
a = np.random.randint(100,size=5)
a

array([ 0, 50, 95, 43, 50])

In [21]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

238
238
47.6
50.0
30.150290214191973


In [22]:
np.sort(a)

array([ 0, 43, 50, 50, 95])

In [23]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

43.0
50.0
50.0


### Broadcasting

In [24]:
a =np.arange(5)
b =np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [25]:
a =np.arange(5)
b =np.arange(5)
a+b

array([0, 2, 4, 6, 8])

In [26]:
a =np.arange(10).reshape(5,2)
b =np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [27]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
b

array([0, 1])

In [29]:
a =np.arange(10).reshape(5,2)
b =np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

In [30]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
b

array([0, 1, 2, 3, 4])

In [32]:
a =np.arange(15).reshape(3,5,1)
b =np.arange(5)
a+b

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8]],

       [[ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]],

       [[10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15],
        [12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [33]:
a =np.arange(25).reshape(1,5,5)
b =np.arange(5)
a+b

array([[[ 0,  2,  4,  6,  8],
        [ 5,  7,  9, 11, 13],
        [10, 12, 14, 16, 18],
        [15, 17, 19, 21, 23],
        [20, 22, 24, 26, 28]]])

In [34]:
a =np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [35]:
np.random.seed(5)
a = np.random.randint(50,size=10)
b = np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [36]:
help(np.ramdom.seed)

AttributeError: module 'numpy' has no attribute 'ramdom'

In [37]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [38]:
a

array([35, 14, 47, 38, 16,  9,  8, 36, 39, 27])

In [39]:
b

array([48, 30, 16,  7, 12, 15, 49, 39, 16, 27])

In [40]:
maxnumber_vec = np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

stacking( vstack,hstack)

In [41]:
a = np.arange(6)
b = np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [42]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [43]:
a = np.arange(6).reshape(2,3)
b = np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [45]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [46]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 

In [47]:
help(np.matmul)

Help on ufunc object:

matmul = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arra